* Codigo de Coducta
  
*** 1. Propósito
El objetivo principal de Club de Algorímtia es crear una comunidad inclusiva de aprendizaje, específicamente de temas relacionados con las ciencias de la computación, el desarrollo de software y el crecimiento de carrera en áreas de tecnología. Como tal, estamos comprometidos a generar un ambiente de convivencia, donde se apoye sin discriminación alguna el crecimiento de cada uno de sus miembros a través de los canales de comunicación dispuestos en la comunidad.
Este código de conducta resume nuestras expectativas para los miembros de la comunidad, además de consecuencias para aquellos que lo incumplan.
Invitamos a todos y todas que apoyen este código de conducta pues creemos que puede contribuir al crecimiento de todas las personas que hacen parte, y que buscan compartir o aprender temas relacionados a los ya descritos.
     
*** 2. Civismo en el Club.
Otro objetivo de este Código de Conducta es explicar de manera concreta lo que creemos que es el comportamiento adecuado para una counidad de este tipo, además apoyando el surgimiento de más comunidades que también busquen ayudar a las personas en sus procesos de aprendizaje y de crecimiento de carrera.
Si tienen ideas de cómo podemos mejorar la convivencia, los recursos y el aprendizaje del grupo, están completamente bienvenidos y bienvenidas a decirlo a los administradores que tomarán pronta consideración de las sugerencias e ideas.
     
*** 3. Comportamiento esperado
**** Participa de manera auténtica y activa. Al hacerlo, contribuyes a la salud y la longevidad de esta comunidad.
**** Ejercita la consideración y el respeto en tus comunicaciones y acciones.
**** Intenta colaborar en lugar de generar conflicto.
**** Absténte de adoptar una conducta y un lenguaje degradantes, discriminatorios, abusivos o acosadores.
**** Sé consciente de tu entorno y de tus compañeros participantes. Alerta a líderes de la comunidad si notas una situación peligrosa, alguien en apuros, o violaciones de este Código de Conducta, incluso si parecen intrascendentes.
**** Intenta apoyar el crecimiento de todos y cada uno de los miembros del Club de Algorítmia.
     
*** 4. Comportamientos inaceptables
Comportamientos inaceptables incluyen: intimidación, acoso, abuso, discriminación, comunicación despectiva o degradante o acciones por cualquier participante en nuestra comunidad ya sea en internet, en todos los eventos relacionados y en las comunicaciones uno-a-uno que se realizan en el contexto de la comunidad. 
El acoso incluye: comentarios nocivos o perjudiciales, verbales o escritos relacionados con el género, la orientación sexual, raza, religión, discapacidad, estatus social, nacionalidad; uso inadecuado de desnudos y / o imágenes sexuales en espacios de comunicación, intimidación deliberada, acecho o seguimiento; fotografías o grabaciones acosadoras; interrupción sostenida de charlas y otros eventos; contacto inapropiado, y atención sexual no deseada.

*** 5. Consecuencias de comportamiento inaceptable
**** El comportamiento inaceptable, como el descrito en la sección anterior, no será tolerado.
**** Se espera que las personas a las que se les llame la atención al incumplir alguna de estas normas, cambien el comportamiento de forma inmediata.
**** Si un miembro de la comunidad participa en una conducta inaceptable, y tras un llamado de atención no corrige su comportamiento, las consecuencias dependiendo el caso pueden ser de prohibición temporal o expulsión permanente del espacio de aprendizaje.

*** 6. Si usted es testigo de comportamiento inaceptable
Si eres víctima o testigo de una conducta inaceptable, o tienes cualquier inquietud, por favor comunícate con un lider de la comunidad lo antes posible, a través de los canales del Discord.

*** 7. Políticas de moderación
Estas son las políticas para mantener los estándares de conducta en nuestra comunidad en los canales de chat, meetups asociados, conferencias, grupos de estudio, y eventos virtuales:
+ Palabras que violen las normas de Código de Conducta, incluyendo comentarios odiosos, hirientes, opresivos,  o excluyentes, no están permitidos. (Se permite las "malas palabras", pero nunca enfocadas hacia otro usuario/asistente, y nunca de una manera despectiva.)
+ Comentarios que los líderes y moderadores encuentren inapropiados tampoco están permitidos, así aparezcan en el código de conducta o no.
+ Los líderes o moderadores primero deberán responder a dichos comentarios con una advertencia.
+ Si la advertencia es ignorada, el miembro será expulsado del club o evento virtual para que evalúe su comportamiento.
+ Si el usuario/asistente regresa y continúa sin seguir el código de conducta o comportándose de manera indebida, será expulsado del Club de forma indefinida.
+ Los líderes o moderadores pueden retractar la expulsión a su discreción si esta se trata de una primera infracción y se ha ofrecido una disculpa sincera a quien ofendieron.
+ Si un lider o moderador expulsa a alguien y usted cree que fue una expulsión sin causa, contacte a ese miembro, o a un lider diferente en privado. Quejas sobre expulsiones en medios abiertos, sociales, u otros canales no son permitidas y conllevaran a más expulsiones.
+ Los líderes y moderadores se rigen por un nivel más alto que otros miembros de la comunidad. Si un organizador crea una situación inadecuada, este será juzgado con un estándar más alto.

*** 8. Roles
Los líderes en el Discord son aquellos que tengan rol @Admin o @lideres. A ellos pueden dirigir inquietudes, sugerencias y reclamos.
  
En el Club de Algorítmia nos esforzamos por ir un paso más allá y cuidar el uno del otro. No se limite a tratar de mostrar su excelencia técnica, trate también de ser la mejor persona posible. En particular, evite tocar temas ofensivos o sensibles, especialmente si están fuera del tema tratado; esto muy a menudo conduce a peleas innecesarias, sentimientos heridos, y a daños en la confianza; peor aún, puede conducir a que personas se alejen de la comunidad en su totalidad.

De la misma forma, si alguien está en desacuerdo con algo que usted dijo o hizo, resista el impulso de estar a la defensiva. Simplemente pare de hacer o decir lo que fuera que causó la queja y pida disculpas. Hay buenas probabilidades de que usted se pudo haber comunicado mejor, incluso si usted siente que fue malinterpretado o injustamente acusado, - recuerde que es su responsabilidad hacer que sus compañeras y compañeros de colombia.dev estén cómodos.

Todo el mundo busca harmonía en este espacio que está hecho para el aprendizaje y la generación de conocimiento. Todos y todas estamos aquí, ante todo, porque queremos hablar de los temas que nos gustan. Por lo general, la gente está dispuesta a asumir buenas intenciones y perdonar, siempre.


*** 9. Licencia y atribución
**** Este código de conducta se distribuye bajo una licencia [[http://creativecommons.org/licenses/by-sa/3.0/][Creative Commons – ShareAlike (BY-SA)]]
**** Adaptado del [[https://github.com/colombia-dev/codigo-de-conducta][Código de Conducta de Colombia-Dev]]

